spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ms_common_stock

eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery-server:8083/eureka
  instance:
    prefer-ip-address: true
